name: buangin
description: "aplikasi bank samapah"
publish_to: 'none' # Remove this line if you wish to 


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  device_preview:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.0.0
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.0
  location: ^5.0.3
  geocoding: ^2.1.0
  provider: ^6.1.2
  flutter_native_splash: ^2.2.19
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1  # Gunakan versi terbaru
  cloud_firestore: ^5.0.0
  flutter_launcher_icons: ^0.14.2


flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"  # Path gambar ikon Anda

flutter:
  assets:
   - lib/assets/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/static/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700
  uses-material-design: true




