// firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUGWPTQDSRmfWaRjelehDXc_p9IeTPWqs',
    appId: '1:795190039393:web:237c08444faed475acab20',
    messagingSenderId: '795190039393',
    projectId: 'buangin-e80f1',
    authDomain: 'buangin-e80f1.firebaseapp.com',
    storageBucket: 'buangin-e80f1.firebasestorage.app',
    measurementId: 'G-P8M9331ZGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvemo0uCKUGQ57k2g-xOQfbEmpC1WSaDU',
    appId: '1:795190039393:android:367ae1370df066a1acab20',
    messagingSenderId: '795190039393',
    projectId: 'buangin-e80f1',
    storageBucket: 'buangin-e80f1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUGWPTQDSRmfWaRjelehDXc_p9IeTPWqs',
    appId: '1:795190039393:web:be7c9b2b2a5a3cc4acab20',
    messagingSenderId: '795190039393',
    projectId: 'buangin-e80f1',
    authDomain: 'buangin-e80f1.firebaseapp.com',
    storageBucket: 'buangin-e80f1.firebasestorage.app',
    measurementId: 'G-KLEVQF12F6',
  );

}